import type { Metadata } from "next";
import { getPosts } from "@/lib/getPosts";
import PostList from "@/components/PostList";

const siteUrl =
  process.env.NEXT_PUBLIC_SITE_URL || "https://superfast.vercel.app";

export const metadata: Metadata = {
  title: "Super Fast Next Blog",
  description: "Read the latest posts generated by AI on Super Fast Next Blog.",
  openGraph: {
    title: "Super Fast Next Blog",
    description:
      "Read the latest posts generated by AI on Super Fast Next Blog.",
    url: siteUrl,
    siteName: "Super Fast Next Blog",
    images: [
      {
        url: `${siteUrl}/api/og?slug=homepage`,
        width: 1200,
        height: 630,
        alt: "Super Fast Next Blog Homepage",
      },
    ],
    locale: "en-US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Super Fast Next Blog",
    description:
      "Read the latest posts generated by AI on Super Fast Next Blog.",
    images: [`${siteUrl}/api/og?slug=homepage`],
  },
  alternates: {
    canonical: siteUrl,
  },
};

export default async function Home() {
  const posts = await getPosts();

  if (posts.length === 0) {
    return (
      <div>
        <p className="text-center text-gray-500">No posts found</p>
      </div>
    );
  }
  return (
    <main>
      <PostList posts={posts} />
    </main>
  );
}
